services:
  - type: web
    name: stock-flow-api-mvp
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: meu-postgres
          property: connectionString

databases:
  - name: meu-postgres
    plan: free
